from __future__ import annotations

from pathlib import Path
from collections.abc import Callable, Mapping, Sequence
from typing import Any
import numpy as np
import pandas as pd
from .objects import *

r_reference_version: str
__version__: str

def apply_gazepoint_calibrator(calibrator: 'GP3MLCalibrator', probability: 'Sequence[float] | np.ndarray') -> 'np.ndarray': ...
def apply_gazepoint_decision_rule(rule: 'GP3MLDecisionRule', probability: 'Sequence[float]', positive: 'Any', negative: 'Any', abstain_label: 'str' = ...) -> 'pd.Categorical': ...
def as_gp3ml_data(x: 'Any', *args: 'Any', **kwargs: 'Any') -> 'pd.DataFrame': ...
def assert_gp3ml_engine_available(engine: 'str', check_keras_backend: 'bool' = ...) -> 'bool': ...
def assert_gp3ml_use_case(task: 'GP3MLTask', data: 'pd.DataFrame | None' = ...) -> 'bool': ...
def assess_gazepoint_calibration(truth: 'Sequence[object] | pd.Series', probability: 'Sequence[float] | np.ndarray', positive: 'str | None' = ..., bins: 'int' = ..., bootstrap: 'int' = ..., conf_level: 'float' = ..., seed: 'int' = ...) -> 'GP3MLCalibrationAssessment': ...
def assess_gazepoint_conformal_coverage(object: 'GP3MLConformal', truth: 'Sequence[Any]', interval: 'pd.DataFrame | None' = ..., set: 'pd.DataFrame | None' = ..., unit: 'Sequence[Any] | None' = ...) -> 'GP3MLConformalCoverage': ...
def audit_gazepoint_abstention(truth: 'Sequence[Any]', decision: 'Sequence[Any]', abstain_label: 'str' = ...) -> 'GP3MLAbstentionAudit': ...
def audit_gazepoint_dataset_shift(development: 'pd.DataFrame', external: 'pd.DataFrame', predictors: 'Sequence[str] | None' = ..., thresholds: 'Mapping[str, float] | None' = ...) -> 'GP3MLDatasetShiftAudit': ...
def audit_gazepoint_group_folds(x: 'GazepointGroupFolds') -> 'GazepointGroupFoldsAudit': ...
def audit_gazepoint_missingness_shift(development: 'pd.DataFrame', external: 'pd.DataFrame', predictors: 'Sequence[str] | None' = ..., review_delta: 'float' = ..., fail_delta: 'float' = ...) -> 'GP3MLMissingnessShiftAudit': ...
def audit_gazepoint_ml_leakage(analysis: 'pd.DataFrame', assessment: 'pd.DataFrame', outcome: 'str', predictors: 'list[str] | tuple[str, ...] | str', participant_id: 'str | None' = ..., trial_id: 'str | None' = ..., stimulus_id: 'str | None' = ..., generalization_target: 'str' = ..., target_derived: 'list[str] | tuple[str, ...] | str | None' = ..., post_outcome: 'list[str] | tuple[str, ...] | str | None' = ...) -> 'GazepointMLLeakageAudit': ...
def audit_gazepoint_model_robustness(seed_stability: 'Any' = ..., feature_stability: 'Any' = ..., threshold_stability: 'Any' = ..., missingness_stability: 'Any' = ..., relative_sd_review: 'Any' = ..., relative_sd_fail: 'Any' = ...) -> 'Any': ...
def audit_gazepoint_nested_resampling(x: 'GP3MLNestedFolds') -> 'GP3MLNestedResamplingAudit': ...
def audit_gazepoint_plan_deviations(plan: 'GP3MLAnalysisPlan', actual: 'Mapping[str, Any]', fields: 'Sequence[str]' = ...) -> 'GP3MLPlanDeviationAudit': ...
def audit_gazepoint_reproducibility(paths: 'Sequence[str | Path] | str | Path', recursive: 'bool' = ..., extensions: 'Sequence[str]' = ...) -> 'GP3MLReproducibilityAudit': ...
def audit_gp3ml_api_stability(registry: 'GP3MLAPIContractRegistry | None' = ...) -> 'GP3MLAPIStabilityAudit': ...
def audit_gp3ml_governance_profile(profile: 'GP3MLGovernanceProfile') -> 'GP3MLGovernanceProfileAudit': ...
def bake_gazepoint_preprocessor(preprocessor: 'GP3MLPreprocessor', new_data: 'pd.DataFrame') -> 'np.ndarray': ...
def bootstrap_gazepoint_metrics(task: 'GP3MLTask', truth: 'Sequence[Any] | pd.Series', prediction: 'Sequence[Any] | pd.Series | None' = ..., probability: 'Sequence[float] | np.ndarray | None' = ..., threshold: 'float' = ..., bootstrap: 'int' = ..., conf_level: 'float' = ..., seed: 'int' = ...) -> 'GP3MLMetricUncertainty': ...
def bootstrap_gazepoint_metrics_by_unit(task: 'Any', truth: 'Any', prediction: 'Any' = ..., probability: 'Any' = ..., participant_id: 'Any' = ..., stimulus_id: 'Any' = ..., unit: 'str' = ..., bootstrap: 'int' = ..., conf_level: 'float' = ..., seed: 'int' = ..., threshold: 'float' = ..., stratify_observations: 'bool' = ...) -> 'Any': ...
def capture_gazepoint_environment(packages: 'Sequence[str] | str | None' = ..., root: 'str | Path' = ..., include_renv: 'bool' = ...) -> 'GP3MLEnvironment': ...
def collect_gazepoint_fold_predictions(x: 'Any', include_failed: 'Any' = ...) -> 'Any': ...
def combine_gazepoint_handoffs(handoffs: 'Any', keys: 'Any' = ..., collision: 'str' = ...) -> 'GP3MLHandoffBundle': ...
def compare_gazepoint_environments(reference: 'GP3MLEnvironment', current: 'GP3MLEnvironment') -> 'GP3MLEnvironmentComparison': ...
def compare_gazepoint_models(x: 'GP3MLModelTuning', metrics: 'Any' = ...) -> 'pd.DataFrame': ...
def create_external_validation_report(validation: 'Any', development_metrics: 'Any' = ..., limitations: 'Any' = ...) -> 'Any': ...
def create_gazepoint_decision_rule(metric: 'str', direction: 'str' = ..., threshold: 'float | None' = ..., threshold_origin: 'str' = ..., cost_false_positive: 'float' = ..., cost_false_negative: 'float' = ..., abstention_allowed: 'bool' = ..., abstention_interval: 'Sequence[float] | None' = ..., calibration_source: 'str' = ..., training_partition: 'str' = ..., generalization_target: 'str | None' = ..., scientific_justification: 'str | None' = ...) -> 'GP3MLDecisionRule': ...
def create_gazepoint_feature_manifest(features: 'list[str] | tuple[str, ...] | str', scientific_source: 'Any' = ..., source_table: 'Any' = ..., transformation: 'Any' = ..., availability_stage: 'Any' = ..., prediction_time_available: 'Any' = ..., outcome_derived: 'Any' = ..., post_outcome: 'Any' = ..., identifier: 'Any' = ..., preprocessing_scope: 'Any' = ..., fold_local_required: 'Any' = ..., reviewer_notes: 'Any' = ...) -> 'pd.DataFrame': ...
def create_gazepoint_group_folds(data: 'pd.DataFrame', outcome: 'str', predictors: 'list[str] | tuple[str, ...] | str', feature_manifest: 'pd.DataFrame', generalization_target: 'str', participant_id: 'str | None' = ..., trial_id: 'str | None' = ..., stimulus_id: 'str | None' = ..., v: 'Any' = ..., repeats: 'int' = ..., seed: 'int' = ..., source_row_id: 'str' = ...) -> 'GazepointGroupFolds': ...
def create_gazepoint_handoff(data: 'pd.DataFrame', source_package: 'str', source_version: 'str | None' = ..., producer: 'str | None' = ..., keys: 'Any' = ..., outcome: 'str | None' = ..., predictors: 'Any' = ..., feature_manifest: 'Any' = ..., notes: 'Any' = ...) -> 'GP3MLHandoff': ...
def create_gazepoint_model_artifact(model: 'Any', preprocessor: 'Any' = ..., feature_manifest: 'Any' = ..., task: 'Any' = ..., decision_rule: 'Any' = ..., model_card: 'Any' = ..., reference_data: 'pd.DataFrame | None' = ..., bundle_model: 'bool' = ...) -> 'GP3MLModelArtifact': ...
def create_gazepoint_model_card(model: 'GP3MLModel', intended_use: 'str', evaluation: 'Any' = ..., calibration: 'Any' = ..., feature_manifest: 'Any' = ..., external_validation: 'Any' = ..., limitations: 'Any' = ..., ethical_review: 'Any' = ...) -> 'Any': ...
def create_gazepoint_nested_folds(outer_folds: 'GazepointGroupFolds', inner_v: 'int' = ..., inner_repeats: 'int' = ..., seed: 'int' = ..., continue_on_error: 'bool' = ...) -> 'GP3MLNestedFolds': ...
def create_gazepoint_release_evidence(objects: 'Mapping[str, Any] | None' = ..., files: 'Mapping[str, str | Path] | None' = ..., version: 'str' = ..., notes: 'str | Sequence[str]' = ...) -> 'GP3MLReleaseEvidence': ...
def create_gazepoint_release_model_card(model: 'GP3MLModel', intended_use: 'str', evaluation: 'Any' = ..., selection: 'GP3MLModelSelection | None' = ..., uncertainty: 'GP3MLTargetUncertainty | GP3MLResampleUncertainty | None' = ..., calibration: 'Any' = ..., feature_manifest: 'Any' = ..., transportability: 'GP3MLTransportabilityReport | None' = ..., limitations: 'str | Sequence[str] | None' = ..., ethical_review: 'Any' = ..., deployment_status: 'str' = ...) -> 'GP3MLReleaseModelCard': ...
def create_gazepoint_reproducibility_report(objects: 'Any' = ..., data: 'Any' = ..., seeds: 'Any' = ..., notes: 'Any' = ..., project_path: 'Any' = ...) -> 'Any': ...
def create_gazepoint_synthetic_manifest(outcome: 'str', predictors: 'Sequence[str]', participant_id: 'str' = ..., stimulus_id: 'str' = ..., trial_id: 'str' = ...) -> 'pd.DataFrame': ...
def create_gazepoint_synthetic_task(data: 'pd.DataFrame', workflow: 'str' = ..., generalization_target: 'str' = ...) -> 'Any': ...
def create_gazepoint_tuning_grid(engine: 'Any', engine_grid: 'dict[str, Any] | None' = ..., preprocessor_grid: 'dict[str, Any] | None' = ..., thresholds: 'Any' = ..., complexity: 'Any' = ..., interpretability: 'Any' = ..., labels: 'Any' = ...) -> 'GP3MLTuningGrid': ...
def create_gp3ml_governance_profile(evidence: 'Mapping[str, object]', framework: 'str' = ...) -> 'GP3MLGovernanceProfile': ...
def declare_gazepoint_analysis_plan(research_question: 'Any', scientific_purpose: 'Any', outcome: 'Any', outcome_definition: 'Any', predictors: 'Sequence[str]', generalization_target: 'Any', grouping_variables: 'Sequence[str] | str' = ..., eligible_population: 'Any' = ..., exclusion_rules: 'Sequence[str] | str' = ..., preprocessing_plan: 'Any' = ..., candidate_models: 'Any' = ..., primary_metric: 'Any' = ..., secondary_metrics: 'Sequence[str] | str' = ..., calibration_metric: 'Any' = ..., uncertainty_method: 'Any' = ..., threshold_policy: 'Any' = ..., external_validation_required: 'bool' = ..., seed_strategy: 'Any' = ..., prohibited_interpretations: 'Sequence[str] | str | None' = ...) -> 'GP3MLAnalysisPlan': ...
def declare_gazepoint_external_dataset(data: 'pd.DataFrame', label: 'str', independent: 'bool', origin: 'str', collection_period: 'Any' = ..., participant_id: 'str | None' = ..., stimulus_id: 'str | None' = ..., notes: 'Any' = ...) -> 'GP3MLExternalDatasetDeclaration': ...
def declare_gazepoint_task(data: 'pd.DataFrame', outcome: 'str', purpose: 'str', task_type: 'str' = ..., unit_id: 'str | None' = ..., participant_id: 'str | None' = ..., stimulus_id: 'str | None' = ..., generalization_target: 'str' = ..., positive: 'str | None' = ..., observed_outcome: 'bool' = ..., sensitive_outcome: 'bool' = ...) -> 'GP3MLTask': ...
def diagnose_gazepoint_group_folds(x: 'GazepointGroupFolds', imbalance_review: 'float' = ..., imbalance_fail: 'float' = ...) -> 'GazepointFoldDiagnostics': ...
def evaluate_external_validation(model: 'GP3MLModel', external_data: 'pd.DataFrame', label: 'Any' = ..., threshold: 'Any' = ..., bootstrap: 'Any' = ..., seed: 'Any' = ...) -> 'Any': ...
def evaluate_gazepoint_external_transportability(model: 'GP3MLModel', development_data: 'pd.DataFrame', external_data: 'pd.DataFrame | None' = ..., declaration: 'GP3MLExternalDatasetDeclaration | None' = ..., development_evaluation: 'Any' = ..., threshold: 'float | None' = ..., bootstrap: 'int' = ..., seed: 'int' = ...) -> 'GP3MLTransportabilityReport': ...
def evaluate_gazepoint_feature_stability(features: 'Any', evaluator: 'Any', **kwargs: 'Any') -> 'Any': ...
def evaluate_gazepoint_group_folds(folds: 'GazepointGroupFolds', task: 'GP3MLTask', predictors: 'Sequence[str] | None' = ..., engine: 'Any' = ..., preprocessor_args: 'dict[str, Any] | None' = ..., engine_args: 'dict[str, Any] | None' = ..., threshold: 'float' = ..., seed: 'int' = ..., assess_calibration: 'bool' = ..., calibration_bins: 'int' = ..., calibration_bootstrap: 'int' = ..., keep_models: 'bool' = ..., continue_on_error: 'bool' = ...) -> 'GP3MLResampleEvaluation': ...
def evaluate_gazepoint_missingness_sensitivity(scenarios: 'Any', evaluator: 'Any', **kwargs: 'Any') -> 'Any': ...
def evaluate_gazepoint_nested_resampling(nested_folds: 'GP3MLNestedFolds', task: 'Any', tuning_grid: 'GP3MLTuningGrid', selection_metric: 'str', direction: 'str', predictors: 'Any' = ..., minimum_success_prop: 'float' = ..., tie_breakers: 'Any' = ..., selection_rationale: 'str' = ..., seed: 'int' = ..., keep_models: 'bool' = ..., continue_on_error: 'bool' = ...) -> 'GP3MLNestedEvaluation': ...
def evaluate_gazepoint_seed_stability(seeds: 'Any', evaluator: 'Any', **kwargs: 'Any') -> 'Any': ...
def evaluate_gazepoint_threshold_stability(evaluation: 'Any', metric: 'Any', direction: 'Any' = ..., tolerance: 'Any' = ...) -> 'Any': ...
def evaluate_gazepoint_thresholds(truth: 'Sequence[Any]', probability: 'Sequence[float]', positive: 'Any', thresholds: 'Sequence[float] | None', cost_false_positive: 'float' = ..., cost_false_negative: 'float' = ...) -> 'GP3MLThresholdEvaluation': ...
def fit_gazepoint_calibrator(truth: 'Sequence[object] | pd.Series', probability: 'Sequence[float] | np.ndarray', positive: 'str | None' = ..., method: 'str' = ...) -> 'GP3MLCalibrator': ...
def fit_gazepoint_conformal(truth: 'Sequence[Any]', prediction: 'Sequence[float] | None' = ..., probability: 'Sequence[float] | None' = ..., task_type: 'str' = ..., positive: 'Any' = ..., level: 'float' = ..., calibration_unit: 'str' = ..., unit: 'Sequence[Any] | None' = ..., generalization_target: 'str | None' = ...) -> 'GP3MLConformal': ...
def fit_gazepoint_deep_model(data: 'pd.DataFrame', task: 'GP3MLTask', predictors: 'Sequence[str] | None' = ..., preprocessor: 'GP3MLPreprocessor | None' = ..., hidden_units: 'Sequence[int]' = ..., dropout: 'float' = ..., epochs: 'int' = ..., batch_size: 'int' = ..., validation_split: 'float' = ..., optimizer: 'str | Any' = ..., seed: 'int' = ..., verbose: 'int' = ...) -> 'GP3MLModel': ...
def fit_gazepoint_model(data: 'pd.DataFrame', task: 'GP3MLTask', predictors: 'Sequence[str] | None' = ..., engine: 'str | GP3MLEngine | None' = ..., preprocessor: 'GP3MLPreprocessor | None' = ..., preprocessor_args: 'dict[str, Any] | None' = ..., engine_args: 'dict[str, Any] | None' = ..., seed: 'int' = ..., threshold: 'float' = ...) -> 'GP3MLModel': ...
def fit_gazepoint_preprocessor(data: 'pd.DataFrame', predictors: 'Sequence[str]', numeric_imputation: 'str' = ..., center: 'bool' = ..., scale: 'bool' = ..., novel_level: 'str' = ..., remove_zero_variance: 'bool' = ...) -> 'GP3MLPreprocessor': ...
def gazepoint_classification_metrics(truth: 'Sequence[Any] | pd.Series', probability: 'Sequence[float] | np.ndarray', predicted: 'Sequence[Any] | pd.Series | None' = ..., positive: 'str | None' = ..., threshold: 'float' = ...) -> 'pd.DataFrame': ...
def gazepoint_performance_metrics(task: 'GP3MLTask', truth: 'Sequence[Any] | pd.Series', prediction: 'Sequence[Any] | pd.Series | None' = ..., probability: 'Sequence[float] | np.ndarray | None' = ..., threshold: 'float' = ...) -> 'pd.DataFrame': ...
def gazepoint_regression_metrics(truth: 'Sequence[float] | np.ndarray', prediction: 'Sequence[float] | np.ndarray') -> 'pd.DataFrame': ...
def gp3ml_api_contracts() -> 'GP3MLAPIContractRegistry': ...
def gp3ml_available_engines() -> 'pd.DataFrame': ...
def gp3ml_engine_capabilities(check_keras_backend: 'bool' = ...) -> 'pd.DataFrame': ...
def gp3ml_interop_contracts() -> 'pd.DataFrame': ...
def gp3ml_object_schema(x: 'Any', recursive: 'bool' = ...) -> 'pd.DataFrame': ...
def gp3ml_prohibited_uses() -> 'list[str]': ...
def integrate_black_box_model(name: 'str', fit_fun: 'Callable[..., Any]', predict_fun: 'Callable[..., Any]', supports: 'Sequence[str]' = ..., probability: 'bool' = ..., metadata: 'dict[str, Any] | None' = ..., safety_declaration: 'dict[str, bool] | None' = ...) -> 'GP3MLEngine': ...
def lock_gazepoint_analysis_plan(plan: 'GP3MLAnalysisPlan', plan_id: 'str | None' = ..., locked_at: 'Any' = ...) -> 'GP3MLAnalysisPlan': ...
def normalize_gazepoint_artifact_text(x: 'Sequence[str] | str', project_path: 'str | Path | None' = ...) -> 'Any': ...
def predict_gazepoint_interval(object: 'GP3MLConformal', prediction: 'Sequence[float]') -> 'pd.DataFrame': ...
def predict_gazepoint_set(object: 'GP3MLConformal', probability: 'Sequence[float]') -> 'pd.DataFrame': ...
def restore_gazepoint_model_artifact(artifact: 'Any') -> 'Any': ...
def select_gazepoint_model(x: 'GP3MLModelTuning', metric: 'str', direction: 'str', minimum_success_prop: 'float' = ..., tie_breakers: 'Any' = ..., rationale: 'str | None' = ...) -> 'GP3MLModelSelection': ...
def select_gazepoint_threshold(evaluation: 'GP3MLThresholdEvaluation', metric: 'str', direction: 'str' = ..., threshold_origin: 'str' = ..., training_partition: 'str' = ..., generalization_target: 'str | None' = ..., scientific_justification: 'str | None' = ..., abstention_allowed: 'bool' = ..., abstention_interval: 'Sequence[float] | None' = ...) -> 'GP3MLDecisionRule': ...
def simulate_gazepoint_governed_data(n_participants: 'int' = ..., n_stimuli: 'int' = ..., trials_per_cell: 'int' = ..., seed: 'int' = ...) -> 'pd.DataFrame': ...
def simulate_gazepoint_research_handoffs(n_participants: 'int' = ..., n_stimuli: 'int' = ..., trials_per_stimulus: 'int' = ..., seed: 'int' = ...) -> 'GP3MLResearchBundle': ...
def split_gazepoint_ml_data(data: 'pd.DataFrame', outcome: 'str', predictors: 'list[str] | tuple[str, ...] | str', feature_manifest: 'pd.DataFrame', generalization_target: 'str', participant_id: 'str | None' = ..., trial_id: 'str | None' = ..., stimulus_id: 'str | None' = ..., assessment_prop: 'float' = ..., seed: 'int' = ..., source_row_id: 'str' = ...) -> 'GazepointMLSplit': ...
def summarize_gazepoint_resample_performance(x: 'Any', aggregation: 'Any' = ..., conf_level: 'Any' = ...) -> 'Any': ...
def summarize_gazepoint_resample_uncertainty(evaluation: 'Any', unit: 'str' = ..., conf_level: 'float' = ...) -> 'Any': ...
def summarize_gazepoint_shift(shift: 'GP3MLDatasetShiftAudit', missingness: 'GP3MLMissingnessShiftAudit | None' = ...) -> 'GP3MLShiftSummary': ...
def test_gazepoint_model_portability(artifact: 'Any', newdata: 'Any' = ..., tolerance: 'float' = ..., fresh_process: 'bool' = ...) -> 'GP3MLModelPortability': ...
def train_gazepoint_classifier(data: 'pd.DataFrame', task: 'GP3MLTask', predictors: 'Sequence[str] | None' = ..., engine: 'str | GP3MLEngine' = ..., **kwargs: 'Any') -> 'GP3MLModel': ...
def tune_gazepoint_model(folds: 'Any', task: 'Any', tuning_grid: 'GP3MLTuningGrid', predictors: 'Any' = ..., metrics: 'Any' = ..., seed: 'int' = ..., continue_on_error: 'bool' = ..., keep_evaluations: 'bool' = ...) -> 'GP3MLModelTuning': ...
def validate_gazepoint_analysis_plan(plan: 'Any') -> 'GP3MLAnalysisPlanValidation': ...
def validate_gazepoint_conformal(object: 'Any') -> 'GP3MLConformalValidation': ...
def validate_gazepoint_decision_rule(rule: 'Any', require_threshold: 'bool' = ...) -> 'GP3MLDecisionRuleValidation': ...
def validate_gazepoint_environment(reference: 'GP3MLEnvironment', root: 'str | Path' = ..., include_renv: 'bool' = ...) -> 'GP3MLEnvironmentComparison': ...
def validate_gazepoint_feature_manifest(x: 'pd.DataFrame') -> 'GazepointFeatureManifestValidation': ...
def validate_gazepoint_fold_diagnostics(x: 'GazepointFoldDiagnostics') -> 'GazepointFoldDiagnosticsValidation': ...
def validate_gazepoint_group_folds(x: 'GazepointGroupFolds') -> 'GazepointGroupFoldsValidation': ...
def validate_gazepoint_handoff(x: 'Any') -> 'GP3MLHandoffValidation': ...
def validate_gazepoint_ml_roles(data: 'pd.DataFrame', task: 'GP3MLTask', predictors: 'list[str] | tuple[str, ...] | str', feature_manifest: 'pd.DataFrame | None' = ...) -> 'GP3MLRoleValidation': ...
def validate_gazepoint_ml_split(x: 'GazepointMLSplit') -> 'GazepointMLSplitValidation': ...
def validate_gazepoint_model_artifact(artifact: 'Any', verify_hash: 'bool' = ...) -> 'GP3MLModelArtifactValidation': ...
def validate_gazepoint_model_tuning(x: 'GP3MLModelTuning') -> 'GP3MLModelTuningValidation': ...
def validate_gazepoint_nested_evaluation(x: 'GP3MLNestedEvaluation') -> 'GP3MLNestedEvaluationValidation': ...
def validate_gazepoint_nested_folds(x: 'GP3MLNestedFolds') -> 'GP3MLNestedFoldsValidation': ...
def validate_gazepoint_release_checksums(manifest: 'Any', directory: 'str | Path' = ...) -> 'GP3MLReleaseChecksumValidation': ...
def validate_gazepoint_resample_evaluation(x: 'Any') -> 'Any': ...
def validate_gazepoint_research_bundle(x: 'Any') -> 'GP3MLResearchBundleValidation': ...
def validate_gazepoint_ro_crate(path: 'Any') -> 'Any': ...
def validate_gazepoint_target_uncertainty(x: 'Any') -> 'Any': ...
def validate_gazepoint_transportability(x: 'GP3MLTransportabilityReport') -> 'GP3MLTransportabilityValidation': ...
def validate_gp3ml_object_contract(x: 'Any', registry: 'GP3MLAPIContractRegistry | None' = ...) -> 'GP3MLObjectContractValidation': ...
def with_gazepoint_reproducible_output(code: 'Callable[[], T] | T') -> 'T': ...
def write_external_validation_report(report: 'Any', path: 'Any', overwrite: 'Any' = ...) -> 'Any': ...
def write_gazepoint_analysis_plan(plan: 'GP3MLAnalysisPlan', path: 'str | Path', format: 'str' = ...) -> 'str': ...
def write_gazepoint_feature_manifest_csv(x: 'Any', file: 'str | Path', table: 'str' = ..., overwrite: 'bool' = ..., na: 'str' = ...) -> 'str': ...
def write_gazepoint_fold_diagnostics_csv(x: 'GazepointFoldDiagnostics', directory: 'str | Path', prefix: 'str' = ..., tables: 'Any' = ..., overwrite: 'bool' = ..., na: 'str' = ...) -> 'dict[str, str]': ...
def write_gazepoint_group_folds_csv(x: 'GazepointGroupFolds', directory: 'str | Path', prefix: 'str' = ..., tables: 'Any' = ..., include_fold_data: 'bool' = ..., overwrite: 'bool' = ..., na: 'str' = ...) -> 'dict[str, str]': ...
def write_gazepoint_ml_leakage_audit_csv(x: 'GazepointMLLeakageAudit', file: 'str | Path', table: 'str' = ..., overwrite: 'bool' = ..., na: 'str' = ...) -> 'str': ...
def write_gazepoint_ml_split_csv(x: 'GazepointMLSplit', directory: 'str | Path', prefix: 'str' = ..., tables: 'list[str] | tuple[str, ...] | str' = ..., overwrite: 'bool' = ..., na: 'str' = ...) -> 'dict[str, str]': ...
def write_gazepoint_model_card(card: 'Any', path: 'Any', format: 'Any' = ..., overwrite: 'Any' = ...) -> 'Any': ...
def write_gazepoint_model_tuning(x: 'GP3MLModelTuning', directory: 'str', prefix: 'str' = ..., selection: 'GP3MLModelSelection | None' = ..., overwrite: 'bool' = ...) -> 'dict[str, str]': ...
def write_gazepoint_nested_evaluation(x: 'GP3MLNestedEvaluation', directory: 'str', prefix: 'str' = ..., overwrite: 'bool' = ...) -> 'dict[str, str]': ...
def write_gazepoint_release_checksums(files: 'Sequence[str | Path] | str | Path', path: 'str | Path' = ...) -> 'GP3MLReleaseChecksumManifest': ...
def write_gazepoint_release_model_card(card: 'GP3MLReleaseModelCard', path: 'str | Path', format: 'str' = ..., overwrite: 'bool' = ...) -> 'str': ...
def write_gazepoint_reproducibility_audit(audit: 'GP3MLReproducibilityAudit', directory: 'str | Path' = ..., prefix: 'str' = ..., overwrite: 'bool' = ...) -> 'Any': ...
def write_gazepoint_reproducibility_report(report: 'Any', path: 'Any', overwrite: 'Any' = ...) -> 'Any': ...
def write_gazepoint_resample_evaluation(x: 'Any', directory: 'Any', prefix: 'Any' = ..., overwrite: 'Any' = ...) -> 'Any': ...
def write_gazepoint_ro_crate(path: 'Any', files: 'Any', name: 'Any', description: 'Any', creator_name: 'Any', creator_orcid: 'Any' = ..., license: 'Any' = ..., doi: 'Any' = ..., copy_files: 'Any' = ...) -> 'Any': ...
def write_gazepoint_target_uncertainty(x: 'Any', directory: 'Any', prefix: 'Any' = ..., overwrite: 'Any' = ...) -> 'Any': ...
def write_gazepoint_transportability_report(report: 'GP3MLTransportabilityReport', path: 'str | Path', overwrite: 'bool' = ...) -> 'str': ...
def write_gp3ml_api_contracts(registry: 'GP3MLAPIContractRegistry | None' = ..., directory: 'str' = ..., prefix: 'str' = ..., overwrite: 'bool' = ...) -> 'dict[str, str]': ...
def write_gp3ml_governance_profile(audit: 'GP3MLGovernanceProfileAudit', path: 'str | Path') -> 'str': ...
